// Mocks generated by Mockito 5.4.4 from annotations
// in vanilla_pay_international/test/vanilla_pay_international_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:vanilla_pay_international/src/models/init_payment_response.dart'
    as _i7;
import 'package:vanilla_pay_international/src/models/token_response.dart'
    as _i6;
import 'package:vanilla_pay_international/src/models/transaction_status_response.dart'
    as _i8;
import 'package:vanilla_pay_international/src/service/vpi_service.dart' as _i2;
import 'package:vanilla_pay_international/src/vanilla_pay.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVanillaPayService_0 extends _i1.SmartFake
    implements _i2.VanillaPayService {
  _FakeVanillaPayService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VanillaPay].
///
/// See the documentation for Mockito's code generation for more information.
class MockVanillaPay extends _i1.Mock implements _i3.VanillaPay {
  MockVanillaPay() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.VanillaPayService get vanillaService => (super.noSuchMethod(
        Invocation.getter(#vanillaService),
        returnValue: _FakeVanillaPayService_0(
          this,
          Invocation.getter(#vanillaService),
        ),
      ) as _i2.VanillaPayService);

  @override
  String get keySecret => (super.noSuchMethod(
        Invocation.getter(#keySecret),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#keySecret),
        ),
      ) as String);

  @override
  _i5.Future<_i6.TokenResponse?> generateToken() => (super.noSuchMethod(
        Invocation.method(
          #generateToken,
          [],
        ),
        returnValue: _i5.Future<_i6.TokenResponse?>.value(),
      ) as _i5.Future<_i6.TokenResponse?>);

  @override
  _i5.Future<_i7.InitPaymentResponse?> initializePayment(
    String? token,
    double? montant,
    String? devise,
    String? reference,
    String? panier,
    String? notifUrl,
    String? redirectUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializePayment,
          [
            token,
            montant,
            devise,
            reference,
            panier,
            notifUrl,
            redirectUrl,
          ],
        ),
        returnValue: _i5.Future<_i7.InitPaymentResponse?>.value(),
      ) as _i5.Future<_i7.InitPaymentResponse?>);

  @override
  _i5.Future<_i8.TransactionStatusResponse?> checkTransactionStatus(
    String? token,
    String? paymentLink,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkTransactionStatus,
          [
            token,
            paymentLink,
          ],
        ),
        returnValue: _i5.Future<_i8.TransactionStatusResponse?>.value(),
      ) as _i5.Future<_i8.TransactionStatusResponse?>);

  @override
  bool validateDataAuthenticity(
    String? vpiSignature,
    String? body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateDataAuthenticity,
          [
            vpiSignature,
            body,
          ],
        ),
        returnValue: false,
      ) as bool);
}
